Pin mkl to <2024
While technically upstream uses 2024.2.0, this is causing some of
the calls to fail with an error:

    RuntimeError: MKL FFT error: Intel oneMKL DFTI ERROR: Inconsistent configuration parameters

Force <2024 that seems to work better.

Fixes #301